version: "3.9"

services:
  source_postgres:
    image: postgres:15
    container_name: source_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  destination_postgres:
    image: postgres:15
    container_name: destination_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - etl_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl_scripts:
    build:
      context: ./elt
      dockerfile: Dockerfile
    container_name: etl_scripts
    command: ["python", "elt_script.py"]
    networks:
      - etl_network
    depends_on:
      source_postgres:
        condition: service_healthy
      destination_postgres:
        condition: service_healthy

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    container_name: dbt
    command:
      [
        "run",
        "--profiles-dir",
        "/root",
        "--project-dir",
        "/dbt",
        "--threads",
        "1"
      ]
    networks:
      - etl_network
    volumes:
      - ./elt/custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      etl_scripts:
        condition: service_completed_successfully

networks:
  etl_network:
    driver: bridge



# services:
#   source_postgres:
#     image: postgres:15
#     ports:
#       - "5433:5432"
#     networks:
#       - etl_network
#     environment:
#        POSTGRES_DB: source_db
#        POSTGRES_USER: postgres
#        POSTGRES_PASSWORD: secret
#     volumes:
#       - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql



#   destination_postgres:
#     image: postgres:15
#     ports:
#       - "5434:5432"
#     networks:
#       - etl_network
#     environment:
#       POSTGRES_DB: destination_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: secret
  
#   etl_scripts:
#     build:
#       context: ./elt
#       dockerfile: Dockerfile
#     command: ["python", "elt_script.py"]
#     networks:
#       - etl_network
#     depends_on:
#       - source_postgres
#       - destination_postgres

#   dbt:
#     image: ghcr.io/dbt-labs/dbt-postgres:latest
#     command:
#       [
#         "run",
#         "--profiles-dir",
#         "/root",
#         "--project-dir",
#         "/dbt"
#       ]
#     networks:
#       - etl_network
#     volumes:
#       - ./elt/custom_postgres:/dbt
#       - ~/.dbt:/root
#     depends_on:
#       - etl_scripts
#     environment:
#       DBT_PROFILE: default
#       DBT_TARGET: dev


# networks:
#   etl_network:
#     driver: bridge
      